<a href="https://colab.research.google.com/github/zenialexandre/Statistics/blob/main/numpyDemo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

first_array = np.array([1, 2, 3, 4])
print('first_array = ', first_array)

array_with_zeros = np.zeros((3, 3)) # only passing the dimensions
print('array_with_zeros = ', array_with_zeros)

array_with_ones = np.ones((3, 3))
print('array_with_ones = ', array_with_ones)

empty_array = np.empty((2, 3)) # return random numbers
print('empty_array = ', empty_array)

np_arange = np.arange(12)
print('np_arange = ', np_arange)

np_arange.reshape(3, 4)
print('np_arange reshaped = ', np_arange)

np_linspce = np.linspace(1, 6, 5) # nearly equal spaced elements
print('np_linspce = ', np_linspce)

oneD_array = np.arange(15)
print('oneD_array = ', oneD_array)

twoD_array = oneD_array.reshape(3, 5) # 3 rows and 5 columns
print('twoD_array = \n', twoD_array)

threeD_array = np.arange(27).reshape(3, 3, 3)
print('threeD_array = \n', threeD_array)

first_array =  [1 2 3 4]
array_with_zeros =  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
array_with_ones =  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
empty_array =  [[3.12230516e-316 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]
np_arange =  [ 0  1  2  3  4  5  6  7  8  9 10 11]
np_arange reshaped =  [ 0  1  2  3  4  5  6  7  8  9 10 11]
np_linspce =  [1.   2.25 3.5  4.75 6.  ]
oneD_array =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
twoD_array = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
threeD_array =  [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
